[package]
name = "electrical_outlets"
version = "0.1.0"
authors = ["Marcus Dicander <dicander@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
